// Making superdough's .room() usable on react-native-audio-api's ConvolverNode.
// Three separate problems, all handled by wrapping BaseAudioContext.createReverb:
//
// 1. Crash before the IR exists. ConvolverNode dereferences null internal
//    buffers if it is processed before a buffer is assigned (SIGSEGV in
//    ConvolverNode::performConvolution on the render thread). superdough
//    connects the convolver into the orbit output immediately and assigns
//    `buffer` later, so hold back the convolver's output connection until
//    the buffer is actually set (a node with no output edge is never pulled
//    by the render graph).
// 2. CPU. Uniform partitioned convolution costs ~O(IR length) per render
//    block; superdough's default 2s decay -> 3s IR uses nearly the whole
//    audio-thread budget on a phone (underruns, timing drift). Cap the IR
//    length (MAX_IR_SECONDS); the requested duration is still recorded on
//    the node so superdough's "did the params change?" check doesn't
//    regenerate the IR every hap.
// 3. Level. The convolver's output is much quieter than a browser's for the
//    same settings, so the wet path gets a fixed makeup gain (WET_GAIN).
//
// (The other half of "no reverb at all" was OfflineAudioContext never
// firing `oncomplete`; see rnGlobalPolyfills.ts.)
//
// Not covered: regenerating the IR on a live node (a later `buffer` set while
// the node is being rendered) still races inside the library (upstream PR
// #1309 territory); keep .room() params constant per pattern for now.
//
// With option 'reverbIrCache' on, generated (noise) IRs come from
// reverbIr.ts's cache instead of being regenerated by superdough each time;
// see createCachedReverb below. A user-supplied IR (.ir()) always goes
// through superdough's own createReverb.
//
// With option 'fdnReverb' on (the default), .room() doesn't use a ConvolverNode at all: it gets
// rn-web-audio-compat's C++ feedback-delay-network reverb (createFdnReverbNode),
// whose cost doesn't depend on the reverb length, so the requested length is
// used uncapped. None of the three problems above apply to it (no IR buffer,
// level calibrated to a browser's convolver). Also only for generated IRs.

import type { BaseAudioContext } from 'react-native-audio-api';
import { createFdnReverbNode } from 'rn-web-audio-compat';
import { getStrudelOption } from '../options';
import { getCachedReverbIr } from './reverbIr';

const MAX_IR_SECONDS = 0.6;
const WET_GAIN = 2.5;

type ConnectArgs = [target: unknown, ...rest: unknown[]];

function findAccessor(obj: object, name: string): PropertyDescriptor | undefined {
  let current: object | null = obj;
  while (current) {
    const descriptor = Object.getOwnPropertyDescriptor(current, name);
    if (descriptor) return descriptor;
    current = Object.getPrototypeOf(current);
  }
  return undefined;
}

interface GuardedConvolver {
  connect: (...a: unknown[]) => unknown;
  buffer: unknown;
  duration?: number;
  generate: (d?: number, ...rest: unknown[]) => void;
}

type ReverbArgs = [
  duration?: number,
  fade?: number,
  lp?: number,
  dim?: number,
  ir?: unknown,
  irspeed?: number,
  irbegin?: number,
];

interface ReverbContext {
  createConvolver: () => unknown;
  adjustLength: (duration: number, buffer: unknown, speed?: number, offset?: number) => unknown;
}

// Same shape and bookkeeping as superdough's reverb.mjs createReverb (the properties it records on the node are what
// Orbit.getReverb's hasChanged() checks read), but the noise IR comes from the cache, capped at MAX_IR_SECONDS.
function createCachedReverb(context: BaseAudioContext): GuardedConvolver {
  const ctx = context as unknown as ReverbContext;
  const convolver = ctx.createConvolver() as GuardedConvolver & Record<string, unknown>;
  convolver.generate = (...generateArgs: unknown[]) => {
    const [d = 2, fade = 0.1, lp = 15000, dim = 1000, ir, irspeed, irbegin] = generateArgs as ReverbArgs;
    Object.assign(convolver, { duration: d, fade, lp, dim, ir, irspeed, irbegin });
    const cappedDuration = Math.min(d, MAX_IR_SECONDS);
    if (ir) {
      convolver.buffer = ctx.adjustLength(cappedDuration, ir, irspeed, irbegin);
      return;
    }
    getCachedReverbIr(context, { decayTime: cappedDuration, fadeInTime: fade, lpFreqStart: lp, lpFreqEnd: dim }, (buffer) => {
      convolver.buffer = buffer;
    });
  };
  return convolver;
}

// The node superdough gets back from createReverb(): a C++ kernel node, plus the same generate()/recorded-properties
// contract as reverb.mjs's convolver (Orbit.getReverb calls generate() when .room params change).
function createFdnReverb(context: BaseAudioContext, args: unknown[]): unknown {
  const node = createFdnReverbNode(context) as unknown as Record<string, unknown> & {
    setParams: (p: { decayTime?: number; fadeInTime?: number; lpFreqStart?: number; lpFreqEnd?: number }) => void;
  };
  node.generate = (...generateArgs: unknown[]) => {
    const [d = 2, fade = 0.1, lp = 15000, dim = 1000, ir, irspeed, irbegin] = generateArgs as ReverbArgs;
    Object.assign(node, { duration: d, fade, lp, dim, ir, irspeed, irbegin });
    node.setParams({ decayTime: d, fadeInTime: fade, lpFreqStart: lp, lpFreqEnd: dim });
  };
  (node.generate as (...a: unknown[]) => void)(...args);
  return node;
}

export function installReverbGuard(): void {
  const proto = (globalThis as unknown as { BaseAudioContext: { prototype: Record<string, unknown> } })
    .BaseAudioContext.prototype as unknown as Record<string, (...args: unknown[]) => unknown>;
  const original = proto.createReverb;
  if (typeof original !== 'function') return;

  proto.createReverb = function (this: BaseAudioContext, ...args: unknown[]) {
    if (getStrudelOption('fdnReverb') && !args[4]) {
      return createFdnReverb(this, args);
    }
    const ctx = this as unknown as {
      createGain: () => { gain: { value: number }; connect: (...a: unknown[]) => unknown };
    };

    let convolver: GuardedConvolver;
    let generateNow: (() => void) | null = null;
    if (getStrudelOption('reverbIrCache') && !args[4]) {
      convolver = createCachedReverb(this);
      // Generate only after the buffer guard below is installed: a cache hit sets the buffer synchronously.
      generateNow = () => (convolver.generate as (...a: unknown[]) => void)(...args);
    } else {
      // Cap the very first generation (createReverb calls generate(...) itself).
      const requestedDuration = args[0] as number | undefined;
      args[0] = Math.min(requestedDuration ?? 2, MAX_IR_SECONDS);

      convolver = original.apply(this, args) as GuardedConvolver;
      convolver.duration = requestedDuration;

      // Later regenerations (pattern changed .room params): cap too, but keep the requested duration on the node.
      const originalGenerate = convolver.generate.bind(convolver);
      convolver.generate = (d?: number, ...rest: unknown[]) => {
        originalGenerate(Math.min(d ?? 2, MAX_IR_SECONDS), ...rest);
        convolver.duration = d;
      };
    }

    const bufferAccessor = findAccessor(convolver, 'buffer');
    if (!bufferAccessor?.get || !bufferAccessor.set) {
      generateNow?.();
      return convolver;
    }

    const getBuffer = bufferAccessor.get;
    const setBuffer = bufferAccessor.set;
    const wet = ctx.createGain();
    wet.gain.value = WET_GAIN;
    const realConnect = convolver.connect.bind(convolver);
    let ready = getBuffer.call(convolver) != null;
    let pending: ConnectArgs[] = [];

    const flush = (): void => {
      realConnect(wet);
      pending.forEach((a) => wet.connect(...a));
      pending = [];
    };
    if (ready) flush();

    convolver.connect = (...a: unknown[]) => {
      if (ready) return wet.connect(...a);
      pending.push(a as ConnectArgs);
      return a[0];
    };

    Object.defineProperty(convolver, 'buffer', {
      configurable: true,
      get: () => getBuffer.call(convolver),
      set: (value: unknown) => {
        setBuffer.call(convolver, value);
        if (!ready && value != null) {
          ready = true;
          flush();
        }
      },
    });

    generateNow?.();
    return convolver;
  };
}
