// Writes COVERAGE.md from conformance/rows.ts (npm run coverage). Don't edit COVERAGE.md by hand.
import * as fs from 'fs';
import * as path from 'path';
import { GROUPS, ROWS } from '../conformance/rows';

const label = { yes: 'Yes', partial: 'Partial', no: 'No' } as const;
const cell = (s?: string) => (s ?? '—').replace(/\|/g, '\\|').replace(/\n/g, ' ');

const lines: string[] = [];
lines.push('# Strudel on React Native: feature coverage');
lines.push('');
lines.push('<!-- Generated by scripts/gen-coverage.ts from conformance/rows.ts. Do not edit by hand. -->');
lines.push('');
lines.push(
  "What of Strudel/superdough works on React Native with rn-strudel, how, and where. Each implemented row has a pattern: " +
    'the example app plays it on React Native and checks for sound, and the web demo plays the identical code on stock ' +
    'Strudel in a browser as the reference (one button per row in both; rows marked No have a disabled button). The ' +
    'standard Web Audio API underneath is covered in ' +
    "[rn-web-audio-compat's COVERAGE.md](https://github.com/wwrinkle/rn-web-audio-compat/blob/main/COVERAGE.md)."
);
lines.push('');
for (const group of GROUPS) {
  lines.push(`## ${group}`);
  lines.push('');
  lines.push('| Feature | Covered? | How | Source | Savings | Pattern |');
  lines.push('|---|---|---|---|---|---|');
  for (const r of ROWS.filter((x) => x.group === group)) {
    lines.push(
      `| ${cell(r.name)} | ${label[r.covered]} | ${cell(r.how)} | ${cell(r.source)} | ${cell(r.savings)} | ${r.code ? '`' + cell(r.code) + '`' : '—'} |`
    );
  }
  lines.push('');
}
const yes = ROWS.filter((r) => r.covered === 'yes').length;
const partial = ROWS.filter((r) => r.covered === 'partial').length;
const n = ROWS.length;
lines.push('## Coverage');
lines.push('');
lines.push(
  `${n} features: ${yes} yes, ${partial} partial, ${n - yes - partial} no: **${Math.round((100 * (yes + partial / 2)) / n)}%** ` +
    `(partial counts as half; ${Math.round((100 * (yes + partial)) / n)}% present at all).`
);
lines.push('');
lines.push('## Beyond the patterns');
lines.push('');
lines.push("- Screen lock: `initStrudel()` drives Strudel's scheduler from an audio-thread clock and shows the Android playback notification, so patterns keep playing in time with the screen locked (verified on a Pixel 10; on an iPhone, patterns played through lock before the audio clock was added, and this version has not been run there yet).");
lines.push('- `engine.evaluate(code)`: run pattern code from text (the Function() form of eval, which Hermes supports).');
lines.push('- Options (`setStrudelOptions`): `fdnReverb`, `reverbIrCache`, `crackleCache`, all on by default.');
lines.push('');
fs.writeFileSync(path.resolve(__dirname, '..', 'COVERAGE.md'), lines.join('\n'));
console.log(`COVERAGE.md: ${n} rows`);
